require "paper-house"

PaperHouse::ExecutableTask.new :hello


################################################################################
#
# If you want to use non-default compiler like llvm-gcc, please
# specify the cc= property or pass the CC= option to rake command.
#
################################################################################

PaperHouse::ExecutableTask.new :llvm_hello do | task |
  task.cc = "llvm-gcc"
end
