require "paper-house/executable-task"


PaperHouse::ExecutableTask.new :hello do | task |
  task.target_directory = "."
  task.sources = [ "*.c" ]
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
