require "paper-house"

libsqrt = PaperHouse::SharedLibraryTask.new :libsqrt do | task |
  task.library_name = "printsqrt"
  task.version = "0.1.0"
  task.target_directory = "objects"
  task.sources = "sources/sqrt.c"
  task.includes = "includes"
  task.cflags = [ "-Werror", "-Wall", "-Wextra" ]
end


task :sqrt => [ :libsqrt, libsqrt.linker_name, libsqrt.soname ]

PaperHouse::ExecutableTask.new :sqrt do | task |
  task.sources = "sources/main.c"
  task.includes = "includes"
  task.ldflags = "-L."
  task.library_dependencies = [ "printsqrt", "m" ]
end

[ libsqrt.linker_name, libsqrt.soname ].each do | each |
  file each do | task |
    symlink File.join( "objects", libsqrt.target_file_name ), task.name
  end

  CLOBBER.include each if FileTest.exists?( each )
end
