require "paper-house"

$libhello = PaperHouse::SharedLibraryTask.new :libhello do | task |
  task.version = "0.1.0"
  task.sources = "hello.c"
end


task :hello => [ :libhello, $libhello.linker_name, $libhello.soname ]

PaperHouse::ExecutableTask.new :hello do | task |
  task.sources = "main.c"
  task.ldflags = "-L."
  task.library_dependencies = "hello"
end

load "symlinks.rake"
