require "paper-house"

libhello = PaperHouse::SharedLibraryTask.new :libhello do | task |
  task.version = "0.1.0"
  task.sources = "hello.c"
end

task :hello => [ libhello.linker_name, libhello.soname ]

file libhello.linker_name => :libhello do | task |
  symlink libhello.target_file_name, task.name
end

file libhello.soname => :libhello do | task |
  symlink libhello.target_file_name, task.name
end

PaperHouse::ExecutableTask.new :hello do | task |
  task.sources = "main.c"
  task.ldflags = "-L."
  task.library_dependencies = "hello"
end


################################################################################
#
# If you want to use non-default compiler like llvm-gcc,
# please specify the cc= property or pass the CC= option to rake command.
#
################################################################################

task :llvm_hello => [ libhello.linker_name, libhello.soname ]

PaperHouse::ExecutableTask.new :llvm_hello do | task |
  task.sources = "main.c"
  task.cc = "llvm-gcc"
  task.ldflags = "-L."
  task.library_dependencies = "hello"
end
