require "paper-house"

libhello = PaperHouse::SharedLibraryTask.new :libhello do | task |
  task.version = "0.1.0"
  task.sources = "hello.c"
end

task :hello => [ libhello.linker_name, libhello.soname ]

file libhello.linker_name => :libhello do | task |
  symlink libhello.target_file_name, task.name
end

file libhello.soname => :libhello do | task |
  symlink libhello.target_file_name, task.name
end

CLOBBER.include libhello.linker_name
CLOBBER.include libhello.soname

PaperHouse::ExecutableTask.new :hello do | task |
  task.sources = "main.c"
  task.cc = "llvm-gcc"
  task.ldflags = "-L."
  task.library_dependencies = "hello"
end
