require "paper-house"

task :hello => :libhello

PaperHouse::StaticLibraryTask.new :libhello do | task |
  task.library_name = "hello"
  task.target_directory = "objects"
  task.sources = "sources/hello.c"
  task.includes = "includes"
  task.cflags = [ "-Werror", "-Wall", "-Wextra" ]
end

PaperHouse::ExecutableTask.new :hello do | task |
  task.sources = "sources/main.c"
  task.includes = "includes"
  task.ldflags = "-Lobjects"
  task.library_dependencies = [ "hello" ]
end
