require 'paper_house'

task :hello => :libhello

PaperHouse::StaticLibraryTask.new :libhello do | task |
  task.library_name = 'hello'
  task.target_directory = 'objects'
  task.sources = 'sources/hello.c'
  task.includes = 'includes'
  task.cflags = %w(-Werror -Wall -Wextra)
end

PaperHouse::ExecutableTask.new :hello do | task |
  task.sources = 'sources/main.c'
  task.includes = 'includes'
  task.ldflags = '-Lobjects'
end
