require "paper-house"

task :hello => :libhello

PaperHouse::StaticLibraryTask.new :libhello do | task |
  task.sources = "hello.c"
end

PaperHouse::ExecutableTask.new :hello do | task |
  task.ldflags = "-L."
  task.sources = "main.c"
  task.library_dependencies = "hello"
end


################################################################################
#
# If you want to use non-default compiler like llvm-gcc,
# please specify the cc= property or pass the CC= option to rake command.
#
################################################################################

task :llvm_hello => :libhello

PaperHouse::ExecutableTask.new :llvm_hello do | task |
  task.cc = "llvm-gcc"
  task.ldflags = "-L."
  task.sources = "main.c"
  task.library_dependencies = "hello"
end
